name: shortest_way_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  percent_indicator: ^4.2.2

  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Data classes
  freezed_annotation: ^2.1.0

  # API
  dio: ^4.0.6
  retrofit: ^3.3.1
  json_annotation: ^4.7.0

  # State managment
  flutter_bloc: ^8.1.1
  async_redux: ^17.0.1

  # Rx
  rxdart: ^0.27.4

  # Storage
  shared_preferences: ^2.0.15

  # Other
  useful_extensions: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  injectable_generator: ^1.5.4
  dart_code_metrics: ^4.19.1
  retrofit_generator: ^4.2.0
  freezed: ^2.1.0+1
  test: ^1.21.4

flutter:
  uses-material-design: true
  generate: true
